[project]
name = "anki-periodic-table-memory-pegs"
version = "0.1.0"
description = "Periodic Table flashcard deck for Anki"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "genanki>=0.13.1",
    "markdown2>=2.5.3",
]
